/*
 * Calender Api
 * Api to book meetings
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.freightfox.calender.model.recommendations;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * RecommendationRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-12T10:01:07.549Z")
public class RecommendationRequest {
  @SerializedName("employees")
  private List<String> employees = null;

  @SerializedName("date")
  private String date = null;

  public RecommendationRequest employees(List<String> employees) {
    this.employees = employees;
    return this;
  }

  public RecommendationRequest addEmployeesItem(String employeesItem) {
    if (this.employees == null) {
      this.employees = new ArrayList<String>();
    }
    this.employees.add(employeesItem);
    return this;
  }

   /**
   * List of employees
   * @return employees
  **/
  @ApiModelProperty(value = "List of employees")
  public List<String> getEmployees() {
    return employees;
  }

  public void setEmployees(List<String> employees) {
    this.employees = employees;
  }

  public RecommendationRequest date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendationRequest recommendationRequest = (RecommendationRequest) o;
    return Objects.equals(this.employees, recommendationRequest.employees) &&
        Objects.equals(this.date, recommendationRequest.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employees, date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendationRequest {\n");
    
    sb.append("    employees: ").append(toIndentedString(employees)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

